export const sifmaxServiceBook = [
  {
    title: 'CROTCH',
    price: '20,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'YEBO',
    price: '25,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'STICH',
    price: '30,000+',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'KNOTLES',
    price: '35,000+',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'FRENCH CURLS SHORT',
    price: '100,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'FRENCH CURLS LONG',
    price: '120,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'BONE STRAIGHT',
    price: '120,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'GYPS LOCS',
    price: '70,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'RIVER LOCS',
    price: '70,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'BUTTERFLY LOCS',
    price: '50,000-100,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'FULANI BRAIDS',
    price: '35,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'BAHAMA TWIST',
    price: '65,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'KINKY',
    price: '50,000/65,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'MICRO TWIST',
    price: '100,000-150,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'NATURAL TWIST EXTENSION',
    price: '60,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'PASSION TWIST SHORT',
    price: '45,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'PASSION TWIST LONG',
    price: '55,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'SELFIE/JOJO',
    price: '35,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'SUNSHINE/VIBRATION',
    price: '35,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'HAVANA',
    price: '35,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'SENSATIONAL BRAIDS SHORT',
    price: '45,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'SENSATIONAL BRAIDS LONG',
    price: '55,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'NORMAL BRAIDS',
    price: '30,000+',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'SEMI HUMANI HAIR',
    price: '50,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'BRAIDS REPAIR FRONT',
    price: '10,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'BRAIDS REPAIR ROUND',
    price: '15,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'FLUFFY LOOSE BRAIDS',
    price: '25,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'WANDY CURL',
    price: '45,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'AFRO BULK HUMAN HAIR',
    price: '220,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'DEEP WAVE',
    price: '60,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'WATER WAVE',
    price: '45,000',
    category: 'HAIR STYLES AND BRAIDS',
    id: 'hair',
  },
  {
    title: 'TWIST',
    price: '20,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'CONROWS',
    price: '25,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'FINGER COIL',
    price: '35,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'DREAD START',
    price: '45,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'DREAD REPAIR',
    price: '15,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'ARTIFICIAL DREADS SHORT',
    price: '80,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'ARTIFICIAL DREADS LONG',
    price: '120,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'DREAD LOCK',
    price: '30,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'RUFF DREAD START',
    price: '25,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'RUFF DREAD REPAIR',
    price: '5,000',
    category: 'NATURAL HAIR',
    id: 'hair',
  },
  {
    title: 'CUSTOMIZATION',
    price: '80,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'BONDING',
    price: '50,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'REPAIR WIG',
    price: '30,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'BONDING/KUSHONEA',
    price: '30,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'FLAT IRON/TONG',
    price: '25,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'HAIR DYE COLOUR',
    price: '40,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'BLACK DYE',
    price: '20,000',
    category: 'WIGS',
    id: 'hair',
  },
  {
    title: 'CURL KIT',
    price: '50,000',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'WASH AND SET ROLLERS',
    price: '15,000',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'WASH AND SET MIRIJA',
    price: '40,000',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'WASH AND SET NET WAVE',
    price: '50,000',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'WASH AND BLOWDRY',
    price: '10,000',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'KUBANA',
    price: '15,000+',
    category: 'SALON SERVICES',
    id: 'hair',
  },
  {
    title: 'START FRESH',
    price: '40,000',
    category: 'CHEMICAL',
    id: 'hair',
  },
  {
    title: 'RE-TOUCH',
    price: '5,000/20,000-30,000',
    category: 'CHEMICAL',
    id: 'hair',
  },
  {
    title: 'STEAMING',
    price: '15,000/20,000',
    category: 'CHEMICAL',
    id: 'hair',
  },
  {
    title: 'CLIENT',
    price: '10,000/15,000',
    category: 'CHEMICAL',
    id: 'hair',
  },
  {
    title: 'NORMAL NAIL POLISH',
    price: '3,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'NORMAL NAIL POLISH WITH NAILS',
    price: '8,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'GEL POLISH',
    price: '10,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'GEL POLISH WITH NAILS',
    price: '15,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'SUPER GEL POLISH',
    price: '20,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'BUILDER GEL POLISH',
    price: '20,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'DIP POWDER (NATURAL NAILS)',
    price: '20,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'POLYGEL (SHORT NAILS)',
    price: '25,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'POLYGEL EXTENSION',
    price: '35,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'ACRYLIC/OMBRE/POWDER NAILS',
    price: '45,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'PARAFFIN MANICURE',
    price: '35,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'NAILS REMOVING',
    price: '3,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'EXTRAS',
    price: '3,000',
    category: 'MANICURE',
    id: 'nail',
  },
  {
    title: 'NORMAL NAIL POLISH',
    price: '3,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'NORMAL NAIL POLISH WITH NAILS',
    price: '8,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'GEL POLISH',
    price: '10,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'TIPS AND GEL POLISH',
    price: '15,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'FOOT SCRUBING',
    price: '5,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'FOOT SCRUBING AND SCRUB',
    price: '20,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'JELLY WAX PEDICURE',
    price: '40,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'FOOT MASSAGE',
    price: '15,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'NAILS REMOVING',
    price: '3,000',
    category: 'PEDICURE',
    id: 'nail',
  },
  {
    title: 'ARMPITS',
    price: '10,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'ARMPITS AND SCRUB',
    price: '20,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'BIKINI',
    price: '25,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'BIKINI AND SCRUB',
    price: '35,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'CHEST',
    price: '25,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'FACE',
    price: '15,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'FULL LEGS',
    price: '25,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'VAJACIAL',
    price: '30,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'VAJACIAL AND BIKINI WAX',
    price: '50,000',
    category: 'WAXING',
    id: 'body',
  },
  {
    title: 'FULL BODY SCRUB',
    price: '100,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'COFFEE BODY SCRUB',
    price: '60,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'COCONUT BODY SCRUB',
    price: '50,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'SWAHILI BODY SCRUB',
    price: '50,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'MILK AND HONEY SCRUB',
    price: '70,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'SIFMAX COMBO (BODY SCRUB, FACIAL, MASSAGE)',
    price: '180,000',
    category: 'SCRUB',
    id: 'body',
  },
  {
    title: 'HALF BODY (30min)',
    price: '30,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'FULL BODY (60min)',
    price: '50,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'HALF BODY MENTHOL (30min)',
    price: '50,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'FULL BODY MENTHOL (60min)',
    price: '80,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'FOUR HANDS (30min)',
    price: '150,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'FOUR HANDS (60min)',
    price: '250,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'BODY TO BODY (30min)',
    price: '180,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'BODY TO BODY (60min)',
    price: '280,000',
    category: 'MASSAGE',
    id: 'body',
  },
  {
    title: 'NORMAL FACIAL (SCRUB, MASK, STEAMING)',
    price: '30,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'NATURAL PRODUCTS',
    price: '40,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'MODERN PRODUCTS',
    price: '50,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'DERMAPLANING FACIAL',
    price: '40,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'HYDRAFACIAL',
    price: '50,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'H2O FACIAL',
    price: '100,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'SIFMAX COMBO FACIAL',
    price: '130,000',
    category: 'FACIAL',
    id: 'facial',
  },
  {
    title: 'FIXING LASHES (HUMAN)',
    price: '30,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'FIXING LASHES (NORMAL)',
    price: '20,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'REFILL',
    price: '15,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'LASH REMOVAL',
    price: '5,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'EYE BROWS',
    price: '30,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'SHAPING',
    price: '3,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'EYE BROWS THREADING',
    price: '15,000',
    category: 'LASHES',
    id: 'facial',
  },
  {
    title: 'SIMPLE MAKE-UP (NO LASHES)',
    price: '20,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'SIMPLE MAKE-UP WITH LASHES',
    price: '30,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'CLASSIC MAKE-UP',
    price: '50,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'ADVANCE CLASSIC',
    price: '100,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'BRIDAL MAKE-UP (BRIDE)',
    price: '200,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'BRIDAL MAKE-UP WITH MATRON',
    price: '300,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'GRADUATE',
    price: '50,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'BIRTHDAY',
    price: '50,000',
    category: 'MAKE UP',
    id: 'facial',
  },
  {
    title: 'BRIDAL ONLY (MAKE-UP, NAILS, FACIAL, HAIR STYLE)',
    price: '350,000',
    category: 'BRIDAL PACKAGES',
    id: 'bridal',
  },
  {
    title: 'BRIDAL WITH MATRON (MAKE-UP, MANICURE, PEDICURE, FACIAL, HAIR STYLES)',
    price: '600,000',
    category: 'BRIDAL PACKAGES',
    id: 'bridal',
  },
  {
    title: 'BRIDAL VIP LOUNGE (MAKE-UP, MANICURE, PEDICURE, FACIAL, HAIR STYLE)',
    price: '450,000',
    category: 'BRIDAL PACKAGES',
    id: 'bridal',
  },
  {
    title: 'BRIDAL WITH MATRON VIP LOUNGE (FULL PACKAGE WITH CHAMPAGNE, DECO, PHOTO SHOOT)',
    price: '750,000',
    category: 'BRIDAL PACKAGES',
    id: 'bridal',
  },
  {
    title: 'BRIDAL WITH MATRON AND FOUR BRAIDS VIP (DELUXE PACKAGE)',
    price: '1,200,000',
    category: 'BRIDAL PACKAGES',
    id: 'bridal',
  },
  {
    title: 'PHOTO SHOOT ROOM AND CHAMPAGNE',
    price: '80,000',
    category: 'ADDITIONAL SERVICES',
    id: 'bridal',
  },
  {
    title: 'DECO',
    price: '150,000',
    category: 'ADDITIONAL SERVICES',
    id: 'bridal',
  },
]

export const sifmaxBook2 = [
  {
    title: 'CROTCH',
    price: 'Tsh. 20,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'YEBO',
    price: 'Tsh. 25,000',
    category: 'hair',
    duration: 150,
  },
  {
    title: 'STICH',
    price: 'Tsh. 30,000+',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'KNOTLES',
    price: 'Tsh. 35,000+',
    category: 'hair',
    duration: 240,
  },
  {
    title: 'FRENCH CURLS SHORT',
    price: 'Tsh. 100,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'FRENCH CURLS LONG',
    price: 'Tsh. 120,000',
    category: 'hair',
    duration: 240,
  },
  {
    title: 'BONE STRAIGHT',
    price: 'Tsh. 120,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'GYPS LOCS',
    price: 'Tsh. 70,000',
    category: 'hair',
    duration: 210,
  },
  {
    title: 'RIVER LOCS',
    price: 'Tsh. 70,000',
    category: 'hair',
    duration: 210,
  },
  {
    title: 'BUTTERFLY LOCS',
    price: 'Tsh. 50,000-100,000',
    category: 'hair',
    duration: 240,
  },
  {
    title: 'FULANI BRAIDS',
    price: 'Tsh. 35,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'BAHAMA TWIST',
    price: 'Tsh. 65,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'KINKY',
    price: 'Tsh. 50,000/65,000',
    category: 'hair',
    duration: 150,
  },
  {
    title: 'MICRO TWIST',
    price: 'Tsh. 100,000-150,000',
    category: 'hair',
    duration: 300,
  },
  {
    title: 'NATURAL TWIST EXTENSION',
    price: 'Tsh. 60,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'PASSION TWIST SHORT',
    price: 'Tsh. 45,000',
    category: 'hair',
    duration: 150,
  },
  {
    title: 'PASSION TWIST LONG',
    price: 'Tsh. 55,000',
    category: 'hair',
    duration: 210,
  },
  {
    title: 'SELFIE/JOJO',
    price: 'Tsh. 35,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'SUNSHINE/VIBRATION',
    price: 'Tsh. 35,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'HAVANA',
    price: 'Tsh. 35,000',
    category: 'hair',
    duration: 150,
  },
  {
    title: 'SENSATIONAL BRAIDS SHORT',
    price: 'Tsh. 45,000',
    category: 'hair',
    duration: 150,
  },
  {
    title: 'SENSATIONAL BRAIDS LONG',
    price: 'Tsh. 55,000',
    category: 'hair',
    duration: 210,
  },
  {
    title: 'NORMAL BRAIDS',
    price: 'Tsh. 30,000+',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'SEMI HUMANI HAIR',
    price: 'Tsh. 50,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'BRAIDS REPAIR FRONT',
    price: 'Tsh. 10,000',
    category: 'hair',
    duration: 45,
  },
  {
    title: 'BRAIDS REPAIR ROUND',
    price: 'Tsh. 15,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'FLUFFY LOOSE BRAIDS',
    price: 'Tsh. 25,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'WANDY CURL',
    price: 'Tsh. 45,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'AFRO BULK HUMAN HAIR',
    price: 'Tsh. 220,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'DEEP WAVE',
    price: 'Tsh. 60,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'WATER WAVE',
    price: 'Tsh. 45,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'TWIST',
    price: 'Tsh. 20,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'CONROWS',
    price: 'Tsh. 25,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'FINGER COIL',
    price: 'Tsh. 35,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'DREAD START',
    price: 'Tsh. 45,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'DREAD REPAIR',
    price: 'Tsh. 15,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'ARTIFICIAL DREADS SHORT',
    price: 'Tsh. 80,000',
    category: 'hair',
    duration: 180,
  },
  {
    title: 'ARTIFICIAL DREADS LONG',
    price: 'Tsh. 120,000',
    category: 'hair',
    duration: 240,
  },
  {
    title: 'DREAD LOCK',
    price: 'Tsh. 30,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'RUFF DREAD START',
    price: 'Tsh. 25,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'RUFF DREAD REPAIR',
    price: 'Tsh. 5,000',
    category: 'hair',
    duration: 45,
  },
  {
    title: 'CUSTOMIZATION',
    price: 'Tsh. 80,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'BONDING',
    price: 'Tsh. 50,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'REPAIR WIG',
    price: 'Tsh. 30,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'BONDING/KUSHONEA',
    price: 'Tsh. 30,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'FLAT IRON/TONG',
    price: 'Tsh. 25,000',
    category: 'hair',
    duration: 45,
  },
  {
    title: 'HAIR DYE COLOUR',
    price: 'Tsh. 40,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'BLACK DYE',
    price: 'Tsh. 20,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'CURL KIT',
    price: 'Tsh. 50,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'WASH AND SET ROLLERS',
    price: 'Tsh. 15,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'WASH AND SET MIRIJA',
    price: 'Tsh. 40,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'WASH AND SET NET WAVE',
    price: 'Tsh. 50,000',
    category: 'hair',
    duration: 120,
  },
  {
    title: 'WASH AND BLOWDRY',
    price: 'Tsh. 10,000',
    category: 'hair',
    duration: 30,
  },
  {
    title: 'KUBANA',
    price: 'Tsh. 15,000+',
    category: 'hair',
    duration: 45,
  },
  {
    title: 'START FRESH',
    price: 'Tsh. 40,000',
    category: 'hair',
    duration: 90,
  },
  {
    title: 'RE-TOUCH',
    price: 'Tsh. 5,000/20,000-30,000',
    category: 'hair',
    duration: 60,
  },
  {
    title: 'STEAMING',
    price: 'Tsh. 15,000/20,000',
    category: 'hair',
    duration: 45,
  },
  {
    title: 'CLIENT',
    price: 'Tsh. 10,000/15,000',
    category: 'hair',
    duration: 30,
  },
  {
    title: 'NORMAL NAIL POLISH',
    price: 'Tsh. 3,000',
    category: 'nail',
    duration: 15,
  },
  {
    title: 'NORMAL NAIL POLISH WITH NAILS',
    price: 'Tsh. 8,000',
    category: 'nail',
    duration: 30,
  },
  {
    title: 'GEL POLISH',
    price: 'Tsh. 10,000',
    category: 'nail',
    duration: 30,
  },
  {
    title: 'GEL POLISH WITH NAILS',
    price: 'Tsh. 15,000',
    category: 'nail',
    duration: 45,
  },
  {
    title: 'SUPER GEL POLISH',
    price: 'Tsh. 20,000',
    category: 'nail',
    duration: 45,
  },
  {
    title: 'BUILDER GEL POLISH',
    price: 'Tsh. 20,000',
    category: 'nail',
    duration: 60,
  },
  {
    title: 'DIP POWDER (NATURAL NAILS)',
    price: 'Tsh. 20,000',
    category: 'nail',
    duration: 60,
  },
  {
    title: 'POLYGEL (SHORT NAILS)',
    price: 'Tsh. 25,000',
    category: 'nail',
    duration: 75,
  },
  {
    title: 'POLYGEL EXTENSION',
    price: 'Tsh. 35,000',
    category: 'nail',
    duration: 90,
  },
  {
    title: 'ACRYLIC/OMBRE/POWDER NAILS',
    price: 'Tsh. 45,000',
    category: 'nail',
    duration: 90,
  },
  {
    title: 'PARAFFIN MANICURE',
    price: 'Tsh. 35,000',
    category: 'nail',
    duration: 60,
  },
  {
    title: 'NAILS REMOVING',
    price: 'Tsh. 3,000',
    category: 'nail',
    duration: 15,
  },
  {
    title: 'EXTRAS',
    price: 'Tsh. 3,000',
    category: 'nail',
    duration: 15,
  },
  {
    title: 'NORMAL NAIL POLISH',
    price: 'Tsh. 3,000',
    category: 'nail',
    duration: 15,
  },
  {
    title: 'NORMAL NAIL POLISH WITH NAILS',
    price: 'Tsh. 8,000',
    category: 'nail',
    duration: 30,
  },
  {
    title: 'GEL POLISH',
    price: 'Tsh. 10,000',
    category: 'nail',
    duration: 30,
  },
  {
    title: 'TIPS AND GEL POLISH',
    price: 'Tsh. 15,000',
    category: 'nail',
    duration: 45,
  },
  {
    title: 'FOOT SCRUBING',
    price: 'Tsh. 5,000',
    category: 'nail',
    duration: 20,
  },
  {
    title: 'FOOT SCRUBING AND SCRUB',
    price: 'Tsh. 20,000',
    category: 'nail',
    duration: 45,
  },
  {
    title: 'JELLY WAX PEDICURE',
    price: 'Tsh. 40,000',
    category: 'nail',
    duration: 75,
  },
  {
    title: 'FOOT MASSAGE',
    price: 'Tsh. 15,000',
    category: 'nail',
    duration: 20,
  },
  {
    title: 'NAILS REMOVING',
    price: 'Tsh. 3,000',
    category: 'nail',
    duration: 15,
  },
  {
    title: 'ARMPITS',
    price: 'Tsh. 10,000',
    category: 'body',
    duration: 15,
  },
  {
    title: 'ARMPITS AND SCRUB',
    price: 'Tsh. 20,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'BIKINI',
    price: 'Tsh. 25,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'BIKINI AND SCRUB',
    price: 'Tsh. 35,000',
    category: 'body',
    duration: 45,
  },
  {
    title: 'CHEST',
    price: 'Tsh. 25,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'FACE',
    price: 'Tsh. 15,000',
    category: 'body',
    duration: 20,
  },
  {
    title: 'FULL LEGS',
    price: 'Tsh. 25,000',
    category: 'body',
    duration: 45,
  },
  {
    title: 'VAJACIAL',
    price: 'Tsh. 30,000',
    category: 'body',
    duration: 45,
  },
  {
    title: 'VAJACIAL AND BIKINI WAX',
    price: 'Tsh. 50,000',
    category: 'body',
    duration: 75,
  },
  {
    title: 'FULL BODY SCRUB',
    price: 'Tsh. 100,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'COFFEE BODY SCRUB',
    price: 'Tsh. 60,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'COCONUT BODY SCRUB',
    price: 'Tsh. 50,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'SWAHILI BODY SCRUB',
    price: 'Tsh. 50,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'MILK AND HONEY SCRUB',
    price: 'Tsh. 70,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'SIFMAX COMBO (BODY SCRUB, FACIAL, MASSAGE)',
    price: 'Tsh. 180,000',
    category: 'body',
    duration: 180,
  },
  {
    title: 'HALF BODY (30min)',
    price: 'Tsh. 30,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'FULL BODY (60min)',
    price: 'Tsh. 50,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'HALF BODY MENTHOL (30min)',
    price: 'Tsh. 50,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'FULL BODY MENTHOL (60min)',
    price: 'Tsh. 80,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'FOUR HANDS (30min)',
    price: 'Tsh. 150,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'FOUR HANDS (60min)',
    price: 'Tsh. 250,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'BODY TO BODY (30min)',
    price: 'Tsh. 180,000',
    category: 'body',
    duration: 30,
  },
  {
    title: 'BODY TO BODY (60min)',
    price: 'Tsh. 280,000',
    category: 'body',
    duration: 60,
  },
  {
    title: 'NORMAL FACIAL (SCRUB, MASK, STEAMING)',
    price: 'Tsh. 30,000',
    category: 'facial',
    duration: 60,
  },
  {
    title: 'NATURAL PRODUCTS',
    price: 'Tsh. 40,000',
    category: 'facial',
    duration: 60,
  },
  {
    title: 'MODERN PRODUCTS',
    price: 'Tsh. 50,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'DERMAPLANING FACIAL',
    price: 'Tsh. 40,000',
    category: 'facial',
    duration: 60,
  },
  {
    title: 'HYDRAFACIAL',
    price: 'Tsh. 50,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'H2O FACIAL',
    price: 'Tsh. 100,000',
    category: 'facial',
    duration: 90,
  },
  {
    title: 'SIFMAX COMBO FACIAL',
    price: 'Tsh. 130,000',
    category: 'facial',
    duration: 120,
  },
  {
    title: 'FIXING LASHES (HUMAN)',
    price: 'Tsh. 30,000',
    category: 'facial',
    duration: 90,
  },
  {
    title: 'FIXING LASHES (NORMAL)',
    price: 'Tsh. 20,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'REFILL',
    price: 'Tsh. 15,000',
    category: 'facial',
    duration: 45,
  },
  {
    title: 'LASH REMOVAL',
    price: 'Tsh. 5,000',
    category: 'facial',
    duration: 15,
  },
  {
    title: 'EYE BROWS',
    price: 'Tsh. 30,000',
    category: 'facial',
    duration: 30,
  },
  {
    title: 'SHAPING',
    price: 'Tsh. 3,000',
    category: 'facial',
    duration: 15,
  },
  {
    title: 'EYE BROWS THREADING',
    price: 'Tsh. 15,000',
    category: 'facial',
    duration: 20,
  },
  {
    title: 'SIMPLE MAKE-UP (NO LASHES)',
    price: 'Tsh. 20,000',
    category: 'facial',
    duration: 45,
  },
  {
    title: 'SIMPLE MAKE-UP WITH LASHES',
    price: 'Tsh. 30,000',
    category: 'facial',
    duration: 60,
  },
  {
    title: 'CLASSIC MAKE-UP',
    price: 'Tsh. 50,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'ADVANCE CLASSIC',
    price: 'Tsh. 100,000',
    category: 'facial',
    duration: 90,
  },
  {
    title: 'BRIDAL MAKE-UP (BRIDE)',
    price: 'Tsh. 200,000',
    category: 'facial',
    duration: 120,
  },
  {
    title: 'BRIDAL MAKE-UP WITH MATRON',
    price: 'Tsh. 300,000',
    category: 'facial',
    duration: 180,
  },
  {
    title: 'GRADUATE',
    price: 'Tsh. 50,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'BIRTHDAY',
    price: 'Tsh. 50,000',
    category: 'facial',
    duration: 75,
  },
  {
    title: 'BRIDAL ONLY (MAKE-UP, NAILS, FACIAL, HAIR STYLE)',
    price: 'Tsh. 350,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'BRIDAL WITH MATRON (MAKE-UP, MANICURE, PEDICURE, FACIAL, HAIR STYLES)',
    price: 'Tsh. 600,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'BRIDAL VIP LOUNGE (MAKE-UP, MANICURE, PEDICURE, FACIAL, HAIR STYLE)',
    price: 'Tsh. 450,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'BRIDAL WITH MATRON VIP LOUNGE (FULL PACKAGE WITH CHAMPAGNE, DECO, PHOTO SHOOT)',
    price: 'Tsh. 750,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'BRIDAL WITH MATRON AND FOUR BRAIDS VIP (DELUXE PACKAGE)',
    price: 'Tsh. 1,200,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'PHOTO SHOOT ROOM AND CHAMPAGNE',
    price: 'Tsh. 80,000',
    category: 'bridal',
    duration: 0,
  },
  {
    title: 'DECO',
    price: 'Tsh. 150,000',
    category: 'bridal',
    duration: 0,
  },
]

export const sifmaxServiceCategories = [
  {
    id: 'hair',

    title: 'Hair Styling',
    description:
      'From cutting-edge cuts to vibrant colors and elegant styling, our expert stylists create looks that enhance your natural beauty.',
    image: '/images/hair.webp',
    alt: 'Hair Styling Services at Sifmax Beauty Parlour',
    searchPlaceholder: 'Search for hair styles, treatments, etc',
    icon: 'hair',
    features: ['Haircuts & Styling', 'Coloring & Highlights', 'Hair Treatments & Masks'],
  },
  {
    id: 'body',
    title: 'Body Care',
    description:
      'Relax and rejuvenate with our therapeutic body treatments designed to relieve stress and enhance your wellbeing.',
    image: '/images/body.webp',
    alt: 'Body Care Services at Sifmax Beauty Parlour',
    searchPlaceholder: 'Search for massages, waxing, etc',
    icon: 'body',
    features: ['Relaxing Massages', 'Body Scrubs & Wraps', 'Waxing & Hair Removal'],
  },
  {
    id: 'nail',
    title: 'Nail Care',
    description:
      'Pamper your hands and feet with our luxurious nail treatments, from classic manicures to artistic nail designs.',
    image: '/images/nail.webp',
    alt: 'Nail Care Services at Sifmax Beauty Parlour',
    searchPlaceholder: 'Search for manicures, pedicures, etc',
    icon: 'nail',
    features: ['Manicures & Pedicures', 'Gel & Acrylic Extensions', 'Nail Art & Designs'],
  },

  {
    id: 'facial',

    title: 'Facial & Makeup',
    description:
      'Revitalize your skin with our premium facials and showcase your beauty with professional makeup applications.',
    image: '/images/facial2.jpg',
    alt: 'Facial and Makeup Services at Sifmax Beauty Parlour',
    searchPlaceholder: 'Search for facials, makeup, lashes etc',
    icon: 'facial',
    features: ['Deep Cleansing Facials', 'Professional Makeup', 'Anti-Aging Treatments'],
  },
  {
    id: 'bridal',

    title: 'Bridal Packages',
    description:
      'Comprehensive bridal beauty packages to ensure you look and feel your absolute best on your special day.',
    image: '/images/bridal.webp',
    alt: 'Bridal Packages at Sifmax Beauty Parlour',
    searchPlaceholder: 'Search for bridal services, packages, etc',
    icon: 'bridal',
    features: ['Bridal Makeup & Hair', 'Pre-Wedding Treatments', 'Group Bridal Packages'],
  },
]
